#!/usr/bin/env php
<?php

ini_set('memory_limit', '256M');
echo("Обрабатываю данные, подождите\n");

$data = prepare();
while (true) {
    $fraze = readline("Введите слово или точную фразу для поиска: ");
    $founds = [];
    foreach ($data as $channel => $titles) {
        foreach ($titles as $title) {
            if (strpos(mb_strtolower($title), mb_strtolower($fraze)) !== false) {
                $founds[$channel][] = $title;
            }
        }
    }
    print_r($founds);
}

function prepare()
{
    $file = "epg2.xml.gz";
    // Check file date
    if (!file_exists($file) || filemtime("epg2.xml.gz") < time() - 86400) {
        // Load file from web
        $url = "http://epg.one/epg2.xml.gz";
        file_put_contents($file, file_get_contents($url));
    }

    $reader = new XMLReader();
    $reader->open("compress.zlib://{$file}");

    $channels = [];
    $data = [];

    while ($reader->read()) {
        if ($reader->nodeType == XMLReader::ELEMENT) {
            switch ($reader->name) {
                case 'channel':
                    $channel_id = (int)$reader->getAttribute('id');
                    while ($reader->read()) {
                        if ($reader->nodeType == XMLReader::ELEMENT && $reader->name == 'display-name') {
                            $channel_name = (string)$reader->readInnerXML();
                            $channels[$channel_id] = $channel_name;
                            break;
                        }
                    }
                    break;

                case 'programme':
                    $start = substr((string)$reader->getAttribute('start'), 0, -8);
                    $end = substr((string)$reader->getAttribute('stop'), 0, -8);
                    $channel = $channels[(int)$reader->getAttribute('channel')];
                    $title = '';
                    while ($reader->read()) {
                        if ($reader->nodeType == XMLReader::ELEMENT && $reader->name == 'title') {
                            $title = (string)$reader->readInnerXML();
                            $data[$channel][] = date("G:i", strtotime($start)) . ' - ' . date("G:i d.m.Y", strtotime($end)) . ' ' . $title;
                            break;
                        }
                    }
                    break;
            }
        }
    }

    $reader->close();

    return $data;
}
